
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/employeemanagement
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=2002

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: employeemanagement
      MYSQL_USER: root
      MYSQL_PASSWORD: 2002
    ports:
      - "3306:3306"
